from dataclasses import dataclass


@dataclass(frozen=True)
class Item:
    item_id: int
    category: str
    popularity: float
    quality: float
    available: bool = True


@dataclass(frozen=True)
class UserProfile:
    user_id: str
    preferred_categories: tuple[str, ...]


@dataclass(frozen=True)
class RequestContext:
    current_category: str | None
    freshness_weight: float


@dataclass(frozen=True)
class RankedItem:
    item_id: int
    score: float


class BatchCandidateStore:
    """
    Stores candidates generated by an offline job.
    """

    def __init__(self) -> None:
        self.candidates_by_user: dict[
            str,
            list[int],
        ] = {}

    def write_candidates(
        self,
        user_id: str,
        candidate_ids: list[int],
    ) -> None:
        self.candidates_by_user[user_id] = list(
            candidate_ids
        )

    def get_candidates(
        self,
        user_id: str,
    ) -> list[int]:
        return list(
            self.candidates_by_user.get(
                user_id,
                [],
            )
        )


def offline_candidate_generation(
    user: UserProfile,
    items: list[Item],
    max_candidates: int = 5,
) -> list[int]:
    """
    Simulate offline candidate generation.

    Prefer items whose category matches the user's
    long-term interests, then use popularity.
    """
    if max_candidates <= 0:
        raise ValueError(
            "max_candidates must be positive."
        )

    scored_items: list[
        tuple[float, int]
    ] = []

    for item in items:
        category_match = (
            1.0
            if item.category
            in user.preferred_categories
            else 0.0
        )

        score = (
            2.0 * category_match
            + item.popularity
        )

        scored_items.append(
            (score, item.item_id)
        )

    scored_items.sort(
        reverse=True
    )

    return [
        item_id
        for _, item_id
        in scored_items[:max_candidates]
    ]


def online_rank(
    candidate_ids: list[int],
    items_by_id: dict[int, Item],
    user: UserProfile,
    context: RequestContext,
    top_k: int = 3,
) -> list[RankedItem]:
    """
    Simulate online ranking.

    Uses:
    - long-term user preference
    - current request category
    - item quality
    - item availability
    """
    if top_k <= 0:
        raise ValueError(
            "top_k must be positive."
        )

    ranked: list[RankedItem] = []

    for item_id in candidate_ids:
        item = items_by_id.get(item_id)

        if item is None:
            continue

        # Online filtering:
        # unavailable items should not be returned.
        if not item.available:
            continue

        long_term_match = (
            1.0
            if item.category
            in user.preferred_categories
            else 0.0
        )

        current_context_match = (
            1.0
            if context.current_category
            == item.category
            else 0.0
        )

        score = (
            1.5 * long_term_match
            + 2.0 * current_context_match
            + 1.2 * item.quality
            + context.freshness_weight
            * item.popularity
        )

        ranked.append(
            RankedItem(
                item_id=item.item_id,
                score=score,
            )
        )

    ranked.sort(
        key=lambda result: result.score,
        reverse=True,
    )

    return ranked[:top_k]


def run_offline_job(
    users: list[UserProfile],
    items: list[Item],
    store: BatchCandidateStore,
) -> None:
    """
    Batch job that precomputes candidates
    for every user.
    """
    for user in users:
        candidates = (
            offline_candidate_generation(
                user=user,
                items=items,
                max_candidates=5,
            )
        )

        store.write_candidates(
            user_id=user.user_id,
            candidate_ids=candidates,
        )


def serve_recommendation(
    user: UserProfile,
    context: RequestContext,
    items_by_id: dict[int, Item],
    candidate_store: BatchCandidateStore,
    top_k: int = 3,
) -> list[RankedItem]:
    """
    Online serving path.

    1. Read precomputed candidates
    2. Apply current context
    3. Filter unavailable items
    4. Return top-k
    """
    candidate_ids = (
        candidate_store.get_candidates(
            user.user_id
        )
    )

    return online_rank(
        candidate_ids=candidate_ids,
        items_by_id=items_by_id,
        user=user,
        context=context,
        top_k=top_k,
    )


def run_demo() -> None:
    items = [
        Item(
            item_id=1,
            category="camera",
            popularity=0.8,
            quality=0.9,
        ),
        Item(
            item_id=2,
            category="travel",
            popularity=0.9,
            quality=0.7,
        ),
        Item(
            item_id=3,
            category="camera",
            popularity=0.6,
            quality=0.95,
        ),
        Item(
            item_id=4,
            category="food",
            popularity=1.0,
            quality=0.8,
        ),
        Item(
            item_id=5,
            category="camera",
            popularity=0.95,
            quality=0.6,
            available=False,
        ),
    ]

    user = UserProfile(
        user_id="user-123",
        preferred_categories=(
            "camera",
            "travel",
        ),
    )

    store = BatchCandidateStore()

    run_offline_job(
        users=[user],
        items=items,
        store=store,
    )

    items_by_id = {
        item.item_id: item
        for item in items
    }

    context = RequestContext(
        current_category="camera",
        freshness_weight=0.2,
    )

    print("Offline candidates")
    print(
        store.get_candidates(
            user.user_id
        )
    )
    print()

    recommendations = serve_recommendation(
        user=user,
        context=context,
        items_by_id=items_by_id,
        candidate_store=store,
        top_k=3,
    )

    print("Online recommendations")

    for result in recommendations:
        print(result)


def main() -> None:
    run_demo()


if __name__ == "__main__":
    main()