# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x0cmodelserving\"\"\n\x0ePredictRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\"%\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\x02\"\x0f\n\rHealthRequest\"0\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x02 \x01(\t2\x9b\x01\n\x0cModelService\x12\x46\n\x07Predict\x12\x1c.modelserving.PredictRequest\x1a\x1d.modelserving.PredictResponse\x12\x43\n\x06Health\x12\x1b.modelserving.HealthRequest\x1a\x1c.modelserving.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=29
  _globals['_PREDICTREQUEST']._serialized_end=63
  _globals['_PREDICTRESPONSE']._serialized_start=65
  _globals['_PREDICTRESPONSE']._serialized_end=102
  _globals['_HEALTHREQUEST']._serialized_start=104
  _globals['_HEALTHREQUEST']._serialized_end=119
  _globals['_HEALTHRESPONSE']._serialized_start=121
  _globals['_HEALTHRESPONSE']._serialized_end=169
  _globals['_MODELSERVICE']._serialized_start=172
  _globals['_MODELSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
