FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY model.py .
COPY serve_model.py .
COPY regression_model.pt .

EXPOSE 8000

CMD [
    "uvicorn",
    "serve_model:app",
    "--host",
    "0.0.0.0",
    "--port",
    "8000"
]